### ISSUE TITLE
Can I ask which version of ldc2 you last built with?

### ISSUE THREAD

**Issue by wilsonk** [bmchtech/rengfx#18] opened 2024-10-08 16:25 UTC
I ran into a few errors when trying to build with the build.sh script and ldc2 version 2.109.1 (llvm-18.1.8). The first one was:

```
Building reng 0.20.0-beta3: building configuration [lib-standard]
source/re/core.d(50,36): Error: undefined identifier `InspectorOverlay`
Error ldc2 failed with exit code 1.
```

Then when I just imported the file where InspectorOverlay was defined, I ran into some other errors, unfortunately. Do you think this is a newer compiler error? Or perhaps something wasn't pushed with the last updates, that affected building?

**Comment by wilsonk** [comment] 2024-10-08 16:33
Oh, hmm, it appears to be a 'release' problem. Things build and the celtest demo runs in debug mode with both dmd and ldc2. Not sure why, but figured you may have an idea why this doesn't build in release mode ;)

**Comment by redthing1** [comment] 2024-10-08 17:14
I know what the issue is, probably accidentally wrapped some stuff in a `debug` block. I can fix it soon

**Comment by redthing1** [comment] 2024-10-08 17:31
Fixed in https://github.com/bmchtech/rengfx/releases/tag/v0.20.0-beta4 with https://github.com/bmchtech/rengfx/commit/075df457f4c391002d752acb9052394cb5ef3c63

**Closed** 2024-10-08 17:40 UTC

**Comment by wilsonk** [comment] 2024-10-08 17:59
Great, thanks for the quick fix, works now ;)
